rvm: 2.0.0-p247
deploy:
  provider: heroku
  api_key:
    secure: bOVx/F4sVDwebnBK32K1a395wMhkaqCz/KHx+3b5MuJVhplO1kexZMjzPYnBb0n9KbcV67uM1tP8M9IcRO3cBI+F3w73/YAPJGTvkLr3Rqtl+/ldjat3lDtHWbIuvi71n5Smv9ahX8kXDV2MNCDXZQQrxyEESk/9NYB1ftuR7/M=
  app: medischrekenen
  on:
    repo: DefactoSoftware/MedischRekenenArcade
    branch: development
bundler_args: --without debug development
cache: bundler
services: redis-server
script:
- bundle exec rake db:test:prepare
- bundle exec rake
before_script:
- cp config/database.travis.yml config/database.yml
- psql -c 'create database mra_test' -U postgres
notifications:
  hipchat:
    rooms:
      secure: PmeANJ22pAsyq/r+iTy2N1Ps42CktFvCG6cnSG2DVsK6FBl+v9fdRRIkZO5mSTKAk2rBwc58GZG610t+vwC4g87NT1BFKaspvMEvNoeXbq/4GwP/Li9mhdbxs20XOCFZu0ClOwCLomXB1FDU0q0yEl1fUSBBNGtDmmtsGUUGINU=
